version: "3.9"
services:
  nginx:
    image: nginx:latest
    ports:
      - 80:80
      - 443:443
    volumes:
      - ./certs/:/etc/nginx/ssl
      - ./conf/:/etc/nginx/conf.d
      - ./includes/:/etc/nginx/includes/
    networks:
      - example1
      - example2
      - grafana

networks:
  example1:
    external:
      name: example1_default
  example2:
    external:
      name: example2_default
  grafana:
    external:
      name: grafana_default
